/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  UserGuides: [
    "user",
    {
      "FAQs": [{
        type: 'autogenerated',
        dirName: 'user/faqs'
      }],
    },
    {
      "User Guides": [{
        type: 'autogenerated',
        dirName: 'user/guides'
      }],
    },
    {
      "Troubleshooting": [
        {
          type: 'autogenerated',
          dirName: 'user/troubleshooting'
        },
        "user/troubleshooting_static/api-token-troubleshooting"
      ]
    }
  ],
  DevGuides: [
    "dev",
    {
      "Create a Module": [
        "modules/overview/getting-started",
        "modules/overview/update-your-manifest",
        "modules/overview/debugging",
        "modules/overview/anatomy",
        "modules/overview/bhm",
        "modules/overview/release"
      ]
    },
    {
      "Module Citizen": [
        "modules/module-citizen/overview",
        "modules/module-citizen/friendly-ui-ux",
        "modules/module-citizen/ensuring-stability",
        "modules/module-citizen/repo-etiquette"
      ]
    },
    {
      "Guides": [
        "modules/guides/settings",
        "modules/guides/gw2api",
        "modules/guides/graphicsdevice",
        "modules/guides/textures",
        "modules/guides/gw2assets",
        "modules/guides/shaders"
      ]
    },
    {
      "API - Controls": [
        "dev/controls/overview",
  
        "dev/controls/colorpicker",
        "dev/controls/detailsbutton",
        "dev/controls/image",
        "dev/controls/label",
        "dev/controls/loadingspinner",
        "dev/controls/panel",
        "dev/controls/standardbutton",
        "dev/controls/standardwindow",
        "dev/controls/tabbedwindow2",
        "dev/controls/textbox"
      ]
    },
    {
      "SSRD": [
        "modules/ssrd/overview",

        "modules/ssrd/registering-modules",
        "modules/ssrd/manage-releases",
        "modules/ssrd/additional-services"
      ]
    }
  ]
};

module.exports = sidebars;